type DemoPassage = {
  id: string;
  text: string;
  author: string;
  bookTitle: string;
  publicationYear: number;
  chapterTitle: string | null;
  sourceUrl: string;
  themes: string[];
};

// These fixtures keep a fresh checkout useful before a database or curated corpus
// exists. Production records come from the verified Standard Ebooks pipeline.
export const demoPassages: readonly DemoPassage[] = [
  {
    id: "demo-pride-prejudice-01",
    text: "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.",
    author: "Jane Austen",
    bookTitle: "Pride and Prejudice",
    publicationYear: 1813,
    chapterTitle: "Chapter I",
    sourceUrl: "https://standardebooks.org/ebooks/jane-austen/pride-and-prejudice",
    themes: ["society", "irony"],
  },
  {
    id: "demo-frankenstein-01",
    text: "Nothing is so painful to the human mind as a great and sudden change.",
    author: "Mary Shelley",
    bookTitle: "Frankenstein",
    publicationYear: 1818,
    chapterTitle: "Chapter XXIII",
    sourceUrl: "https://standardebooks.org/ebooks/mary-shelley/frankenstein",
    themes: ["change", "grief"],
  },
  {
    id: "demo-moby-dick-01",
    text: "There is a wisdom that is woe; but there is a woe that is madness. And there is a Catskill eagle in some souls that can alike dive down into the blackest gorges, and soar out of them again and become invisible in the sunny spaces.",
    author: "Herman Melville",
    bookTitle: "Moby-Dick",
    publicationYear: 1851,
    chapterTitle: "Chapter 96: The Try-Works",
    sourceUrl: "https://standardebooks.org/ebooks/herman-melville/moby-dick",
    themes: ["resilience", "wisdom"],
  },
  {
    id: "demo-jane-eyre-01",
    text: "I am no bird; and no net ensnares me: I am a free human being with an independent will; which I now exert to leave you.",
    author: "Charlotte Brontë",
    bookTitle: "Jane Eyre",
    publicationYear: 1847,
    chapterTitle: "Chapter XXIII",
    sourceUrl: "https://standardebooks.org/ebooks/charlotte-bronte/jane-eyre",
    themes: ["freedom", "selfhood"],
  },
  {
    id: "demo-walden-01",
    text: "I went to the woods because I wished to live deliberately, to front only the essential facts of life, and see if I could not learn what it had to teach, and not, when I came to die, discover that I had not lived.",
    author: "Henry David Thoreau",
    bookTitle: "Walden",
    publicationYear: 1854,
    chapterTitle: "Where I Lived, and What I Lived For",
    sourceUrl: "https://standardebooks.org/ebooks/henry-david-thoreau/walden",
    themes: ["attention", "nature"],
  },
  {
    id: "demo-dorian-gray-01",
    text: "Nowadays people know the price of everything and the value of nothing.",
    author: "Oscar Wilde",
    bookTitle: "The Picture of Dorian Gray",
    publicationYear: 1890,
    chapterTitle: "Chapter IV",
    sourceUrl: "https://standardebooks.org/ebooks/oscar-wilde/the-picture-of-dorian-gray",
    themes: ["value", "society"],
  },
  {
    id: "demo-souls-black-folk-01",
    text: "The problem of the twentieth century is the problem of the color-line—the relation of the darker to the lighter races of men in Asia and Africa, in America and the islands of the sea.",
    author: "W. E. B. Du Bois",
    bookTitle: "The Souls of Black Folk",
    publicationYear: 1903,
    chapterTitle: "The Forethought",
    sourceUrl: "https://standardebooks.org/ebooks/w-e-b-du-bois/the-souls-of-black-folk",
    themes: ["history", "justice"],
  },
  {
    id: "demo-dracula-01",
    text: "There are darknesses in life and there are lights, and you are one of the lights, the light of all lights.",
    author: "Bram Stoker",
    bookTitle: "Dracula",
    publicationYear: 1897,
    chapterTitle: "Chapter XXI",
    sourceUrl: "https://standardebooks.org/ebooks/bram-stoker/dracula",
    themes: ["devotion", "hope"],
  },
  {
    id: "demo-anne-green-gables-01",
    text: "Isn’t it nice to think that tomorrow is a new day with no mistakes in it yet?",
    author: "L. M. Montgomery",
    bookTitle: "Anne of Green Gables",
    publicationYear: 1908,
    chapterTitle: "Chapter XXI",
    sourceUrl: "https://standardebooks.org/ebooks/l-m-montgomery/anne-of-green-gables",
    themes: ["beginnings", "optimism"],
  },
  {
    id: "demo-middlemarch-01",
    text: "But the effect of her being on those around her was incalculably diffusive: for the growing good of the world is partly dependent on unhistoric acts.",
    author: "George Eliot",
    bookTitle: "Middlemarch",
    publicationYear: 1871,
    chapterTitle: "Finale",
    sourceUrl: "https://standardebooks.org/ebooks/george-eliot/middlemarch",
    themes: ["kindness", "legacy"],
  },
  {
    id: "demo-importance-earnest-01",
    text: "The truth is rarely pure and never simple.",
    author: "Oscar Wilde",
    bookTitle: "The Importance of Being Earnest",
    publicationYear: 1895,
    chapterTitle: "Act I",
    sourceUrl: "https://standardebooks.org/ebooks/oscar-wilde/the-importance-of-being-earnest",
    themes: ["truth", "wit"],
  },
  {
    id: "demo-awakening-01",
    text: "The voice of the sea is seductive; never ceasing, whispering, clamoring, murmuring, inviting the soul to wander for a spell in abysses of solitude.",
    author: "Kate Chopin",
    bookTitle: "The Awakening",
    publicationYear: 1899,
    chapterTitle: "Chapter VI",
    sourceUrl: "https://standardebooks.org/ebooks/kate-chopin/the-awakening",
    themes: ["solitude", "desire"],
  },
  {
    id: "demo-great-expectations-01",
    text: "Suffering has been stronger than all other teaching, and has taught me to understand what your heart used to be.",
    author: "Charles Dickens",
    bookTitle: "Great Expectations",
    publicationYear: 1861,
    chapterTitle: "Chapter LIX",
    sourceUrl: "https://standardebooks.org/ebooks/charles-dickens/great-expectations",
    themes: ["suffering", "understanding"],
  },
  {
    id: "demo-leaves-grass-01",
    text: "I am large, I contain multitudes.",
    author: "Walt Whitman",
    bookTitle: "Leaves of Grass",
    publicationYear: 1855,
    chapterTitle: "Song of Myself",
    sourceUrl: "https://standardebooks.org/ebooks/walt-whitman/leaves-of-grass",
    themes: ["identity", "contradiction"],
  },
] as const;
